### ISSUE TITLE
Add mechanism for disposing / deleting a stream(s)

### ISSUE THREAD

**Issue by branimirangelov** [obecto/perper#56]
Deletion of a stream:
- What happens with the data and the streams that are listening?
- Criteria for automatic deletion (temp stream)
- Handle garbage while normal operation (short lived streams).

**Comment by bojidar-bg** [comment]
* Deletion of a stream (cancelling its execution and deleting the underlying cache) was tentatively implemented in d367dde1a4dfebd1c4005826265de432e57471a1. Since this involves deleting the cache, data would be lost and listening streams are likely to receive an exception.
* There is no automatic stream collection at this point. I'm not sure if it is even possible, considering that streams can cause side effects during their execution, and thus even streams without references/listeners might be non-garbage.
* Garbage during normal operation is probably handled by Ephemeral streams that lose their items after all listeners have read them; those were added in 0.6.

Unless different semantics are needed, this issue can be closed; going to do so now and reopen in case there's further discussion.
