### ISSUE TITLE
Data serialization - Capital letters bug.

### ISSUE THREAD

**Issue by radi-cho** [obecto/perper#78]
While experimenting with reading/writing data via the Node.JS Ignite thin client I found an interesting scenario occurring. By default when I am mapping the `SimpleDataStream` to the javascript object data type all the keys begin with a capital letter. 

<img width="369" alt="Screenshot 2021-03-15 at 17 54 53" src="https://user-images.githubusercontent.com/12954909/111182410-8dd52e80-85b7-11eb-928a-702400427514.png">

However, if you run the `ds-python` example first (which adds a new cache entry) and then you run the `ds-node` sample, all the keys start with lowercase letters (not only the newly written one).

<img width="369" alt="Screenshot 2021-03-15 at 18 04 57" src="https://user-images.githubusercontent.com/12954909/111183789-f670db00-85b8-11eb-8828-a7a38b06d499.png">

**Comment by bojidar-bg** [comment]
As all core types (`PerperStream`, `PerperAgent`, etc.) use `camelCase` since 32acf45a7c08544592c1c395491f5613c4846669, this should not be an issue for Perper itself. Once NodeJS support is reintroduced, it might still happen in user code, but then it would be better handled on the [Apache Ignite JIRA](https://issues.apache.org/jira/).

Therefore, closing.
